# Avenues of exploration

There are two main suspected factors of obesity (CDC): 

 + Poor exercise 
 
 and/or 
 + Poor diet 
 
However studies find that 'you can't outrun a bad diet' (Godoy, 2025)
meaning the main contributor of this condition is controlled by the food market.
This combined with the fact that obesity is a modern disease must mean that the 
cause was introduced fairly recently. Here are some factors we will examine in
relation to Obesity to investigate further (Our world on data):

 + Diet (ratio of what foods)
 + GDP
 + Historical change
 + Lifestyle
 + Daily Calories available/consumed
 
 
 
 # Literature Cited  
 
 + “Goal 3 | Department of Economic and Social Affairs.” United Nations, United Nations, sdgs.un.org/goals/goal3. Accessed 8 Apr. 2026.  

 + “Targets of Sustainable Development Goal 3.” World Health Organization, World Health Organization, www.who.int/europe/about-us/our-work/sustainable-development-goals/targets-of-sustainable-development-goal-3. Accessed 8 Apr. 2026. 

 + Godoy, Maria. “You Can’t Outrun a Bad Diet. Food - Not Lack of Exercise - Fuels Obesity, Study Finds.” NPR, NPR, 24 July 2025, www.npr.org/2025/07/24/nx-s1-5477662/diet-exercise-obesity-nutrition. 

 + Our World in Data. “Our World in Data.” Our World in Data, 28 Feb. 2024, ourworldindata.org/. 

 + “Risk Factors for Obesity.” Centers for Disease Control and Prevention, Centers for Disease Control and Prevention, www.cdc.gov/obesity/risk-factors/risk-factors.html. Accessed 8 Apr. 2026. 

 + “Products - Data Briefs - Number 508 - September 2024.” Centers for Disease Control and Prevention, Centers for Disease Control and Prevention, 24 Sept. 2024, www.cdc.gov/nchs/products/databriefs/db508.htm. 

 + “SDG Target 3.3 Communicable Diseases.” World Health Organization, World Health Organization, www.who.int/data/gho/data/themes/topics/sdg-target-3_3-communicable-diseases. Accessed 8 Apr. 2026. 

 + Takian A, Raoofi A, Haghighi H. COVID-19 pandemic: The fears and hopes for SDG 3, with focus on prevention and control of noncommunicable diseases (SDG 3.4) and universal health coverage (SDG 3.8). COVID-19 and the Sustainable Development Goals. 2022:211–34. doi: 10.1016/B978-0-323-91307-2.00014-6. Epub 2022 Jul 29. PMCID: PMC9334993.

 + “Noncommunicable Diseases.” World Health Organization, World Health Organization, www.who.int/news-room/fact-sheets/detail/noncommunicable-diseases. Accessed 8 Apr. 2026. 

 + “Obesity and Overweight.” World Health Organization, World Health Organization, www.who.int/news-room/fact-sheets/detail/obesity-and-overweight#:~:text=While%20these%20countries%20continue%20to,appropriate%20weight%20gain%20during%20pregnancy; Accessed 8 Apr. 2026. 

